# Generated by Django 5.1.6 on 2025-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="開課單位"),
                ),
                (
                    "course_title",
                    models.CharField(max_length=200, verbose_name="課程名稱"),
                ),
                (
                    "instructor",
                    models.CharField(max_length=100, verbose_name="授課老師"),
                ),
            ],
            options={
                "verbose_name": "課程",
                "verbose_name_plural": "課程",
            },
        ),
    ]
